import {newGame,upgradeGame,simulateSet} from '../lib/game.ts';
import {buildReplay} from '../lib/simulation/replay.ts';
const g=upgradeGame(newGame('nva',7));
const M={id:'r',a:'nva',b:'crn',bestOf:3,scoreA:0,scoreB:0,sets:[],label:'R1'};
g.seed=42;const set=simulateSet(g,M);
const rd=buildReplay(set);
const tr=rd.tracks.find(t=>t.side==='A'&&t.slot===4);
console.log('--- A4 keyframes ---');
for(const k of tr.key)console.log(`  t=${k.t.toFixed(2)} ${k.state} [${k.pos.map(n=>n.toFixed(0))}]`);
console.log('--- A4 beats (kill/revive) ---');
for(const b of rd.beats.filter(b=>b.ref&&b.ref.side==='A'&&b.ref.slot===4&&(b.kind==='kill'||b.kind==='revive')))console.log(`  t=${b.t.toFixed(2)} ${b.kind} ${b.text||''}`);
console.log('--- events ---');
set.events.forEach(e=>console.log(`  #${e.index} ${e.phase} ${e.combat?.kind||'-'} kills=${e.combat?.kills?.length||0} clock=${e.combat?.clock||''}`));
